version: "2"

services:
  php_mysql_challs_template:
    build: .
    image: compassctf/php_mysql_challs_template
    restart: always
    ports:
      - "127.0.0.1:15001:80"
    environment:
      - GZCTF_FLAG=flag{test_flag_string_babecafe}