version: "2"

services:
  flask_challs_template:
    build: .
    image: compassctf/flask_challs_template
    restart: always
    ports:
      - "127.0.0.1:15001:9999"
    environment:
      - GZCTF_FLAG=flag{test_flag_string_babecafe}